# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

# Include the latest Ably Library
# Change 'Example' to fit your target name
target 'Example' do 
    pod 'AblyRealtime'
end
